#!/bin/bash

expecthosts='<MD5>  /etc/hosts' #Replace <MD5> with your own hosts' MD5
actualhosts="$(md5sum /etc/hosts)"

echo "Downloading the Hosts file."
cd /var/mobile
if curl -OL <URL>; then #Replace <URL> with your own hosts' URL
    :
else
    exit 1
fi
echo "Moving the Hosts file to /etc"
rm -rf /etc/hosts
mv hosts /etc
echo "Checking md5"
if [ "$actualhosts" == "$expecthosts" ]; then
    echo "Verfied"
    exit 0
else
    echo "Seems like your hosts file is invalid, try again."
    rm -rf /etc/hosts
    cd /var/mobile/ADhosts
    cp hosts /etc
    rm -rf /var/mobile/ADhosts
    exit 1
fi
exit